# Generated by Django 3.0.8 on 2022-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
