# Generated by Django 2.2.10 on 2022-12-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
